### PR TITLE
bsp/u-boot: Fix BOOTCMD for WaRP7

### PR DESCRIPTION
**Pull request by texierp**
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

### CODE REVIEW

**Comment by otavio** [comment]
Hello @texierp; nice to see you around :+1: 

What error happens? also do you mind to extend the commit log a little bit to explain it?

**Comment by texierp** [comment]
It seems the problem comes from #undef CONFIG_BOOTCOMMAND after the inclusion of updatehub-common.h

**Comment by texierp** [comment]
I will update the commit log

**Comment by texierp** [comment]
Updated ! :+1:

**Review by otavio — APPROVED** [review]

**Pull request merged**
